apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapi-deployment
  labels:
    app: demoapi
spec:
  replicas: 3
  template:
    metadata:
      name: demoapi
      labels:
        app: demoapi
    spec:
      containers:
      - name: demoapi
        image: __ACR__/demoapi:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: demoapi


---

apiVersion: v1
kind: Service
metadata:
  name: demoapi-service
spec:
  selector:
    app: demoapi
  ports:
    - port: 80
  type: LoadBalancer
  
  
