version: '3.4'

services:
  demoapi:
    image: demoapi:v3
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - 'ConnectionStrings:sqldb=_AzureSQLConnectionStringEnvValueDocker_'
    ports:
      - "5000:80"
