version: '3.4'

services:
  demoapi:
    image: demoapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - 'ConnectionStrings:sqldb=__AzureSQLConnectionStringEnvValueDocker__'
    ports:
      - "5000:80"
